# Generated by Django 4.0.4 on 2022-07-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodect_desc',
            new_name='product_desc',
        ),
    ]
